### ISSUE TITLE
Should we add hints to pages?

### ISSUE THREAD

**Issue by LunaGmooN** [Vatos2/TBD-Repository#6]
Each window in the Create-A-Character could have a "help button" that explains the rules for that part of the Create-A-Character process. the most obvious thing would be to have a '?' in the corner that when clicked on, has a pop up with the rules. 
Ex: how to decide the values for your Ability Scores (Strength, Dexterity, Constitution, Intelligence, etc..) per the game rules. 
Vote yes or no ... preferably with a why.

**Comment by collinsperry21** [comment]
I vote yes. I like the idea because its not explaining how to use the app but rather how it works in the context of the game.
